"""outbox and job events

Revision ID: 20260903_02_outbox_events
Revises: 20260903_01_baseline
Create Date: 2026-09-17 16:24:43.896803

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260903_02_outbox_events"
down_revision: str | Sequence[str] | None = "20260903_01_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "sequence", name="uq_job_events_job_sequence"),
    )
    op.create_index(
        op.f("ix_job_events_event_type"), "job_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_job_events_job_id"), "job_events", ["job_id"], unique=False
    )
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("aggregate_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("delivery_attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["aggregate_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outbox_messages_aggregate_id"),
        "outbox_messages",
        ["aggregate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_messages_delivered_at"),
        "outbox_messages",
        ["delivered_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_messages_kind"), "outbox_messages", ["kind"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outbox_messages_kind"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_delivered_at"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_aggregate_id"), table_name="outbox_messages")
    op.drop_table("outbox_messages")
    op.drop_index(op.f("ix_job_events_job_id"), table_name="job_events")
    op.drop_index(op.f("ix_job_events_event_type"), table_name="job_events")
    op.drop_table("job_events")
    # ### end Alembic commands ###
