"""immutable artifacts

Revision ID: 20260903_05_artifacts
Revises: 20260903_04_batches
Create Date: 2026-09-17 17:11:45.651148

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260903_05_artifacts"
down_revision: str | Sequence[str] | None = "20260903_04_batches"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("mix_id", sa.String(length=36), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("key", sa.String(length=512), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("algorithm_version", sa.String(length=50), nullable=False),
        sa.Column("media_type", sa.String(length=100), nullable=False),
        sa.Column("byte_length", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["mix_id"],
            ["mixes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_artifacts_key"), ["key"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_artifacts_mix_id"), ["mix_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_artifacts_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_artifacts_role"), ["role"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artifacts_role"))
        batch_op.drop_index(batch_op.f("ix_artifacts_project_id"))
        batch_op.drop_index(batch_op.f("ix_artifacts_mix_id"))
        batch_op.drop_index(batch_op.f("ix_artifacts_key"))

    op.drop_table("artifacts")
    # ### end Alembic commands ###
