"""batches and notifications

Revision ID: 20260903_04_batches_notifications
Revises: 20260903_03_identity_scope
Create Date: 2026-09-17 16:52:31.397125

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260903_04_batches_notifications"
down_revision: str | Sequence[str] | None = "20260903_03_identity_scope"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("dedupe_key", sa.String(length=128), nullable=False),
        sa.Column("deep_link", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_dedupe_key"), ["dedupe_key"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("endpoint_hash", sa.String(length=64), nullable=False),
        sa.Column("encrypted_payload", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("push_subscriptions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_push_subscriptions_endpoint_hash"),
            ["endpoint_hash"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_push_subscriptions_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "notification_deliveries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("notification_id", sa.String(length=36), nullable=False),
        sa.Column("subscription_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["push_subscriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "notification_id", "subscription_id", name="uq_notification_subscription"
        ),
    )
    with op.batch_alter_table("notification_deliveries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_notification_id"),
            ["notification_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_subscription_id"),
            ["subscription_id"],
            unique=False,
        )

    op.create_table(
        "batches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("batches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_batches_project_id"), ["project_id"], unique=False
        )

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("batch_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_jobs_batch_id"), ["batch_id"], unique=False
        )
        batch_op.create_foreign_key("fk_jobs_batch_id", "batches", ["batch_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_jobs_batch_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_jobs_batch_id"))
        batch_op.drop_column("batch_id")

    with op.batch_alter_table("batches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_batches_project_id"))

    op.drop_table("batches")
    with op.batch_alter_table("notification_deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_subscription_id"))
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_notification_id"))

    op.drop_table("notification_deliveries")
    with op.batch_alter_table("push_subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_push_subscriptions_project_id"))
        batch_op.drop_index(batch_op.f("ix_push_subscriptions_endpoint_hash"))

    op.drop_table("push_subscriptions")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_project_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_dedupe_key"))

    op.drop_table("notifications")
    # ### end Alembic commands ###
